// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxspyBWK6oueP9SEOqMeuQg81a-bRP0Mo',
    appId: '1:684634883104:web:128b746bcf9691dbe46845',
    messagingSenderId: '684634883104',
    projectId: 'smart-attendance-9fbcb',
    authDomain: 'smart-attendance-9fbcb.firebaseapp.com',
    storageBucket: 'smart-attendance-9fbcb.firebasestorage.app',
    measurementId: 'G-4KSG307TK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCerKBclGDDH5EgsxS2CEiW3YsO8EdVNTE',
    appId: '1:684634883104:android:0f3382567bb013d9e46845',
    messagingSenderId: '684634883104',
    projectId: 'smart-attendance-9fbcb',
    storageBucket: 'smart-attendance-9fbcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO6Znu_-1d2UPT1zdC2jEjvEorXBN34YI',
    appId: '1:684634883104:ios:1658ce209d377d51e46845',
    messagingSenderId: '684634883104',
    projectId: 'smart-attendance-9fbcb',
    storageBucket: 'smart-attendance-9fbcb.firebasestorage.app',
    iosBundleId: 'com.codecatalyst.smartattendance.smartAttendanceAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO6Znu_-1d2UPT1zdC2jEjvEorXBN34YI',
    appId: '1:684634883104:ios:1658ce209d377d51e46845',
    messagingSenderId: '684634883104',
    projectId: 'smart-attendance-9fbcb',
    storageBucket: 'smart-attendance-9fbcb.firebasestorage.app',
    iosBundleId: 'com.codecatalyst.smartattendance.smartAttendanceAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxspyBWK6oueP9SEOqMeuQg81a-bRP0Mo',
    appId: '1:684634883104:web:48c657eedb6deb16e46845',
    messagingSenderId: '684634883104',
    projectId: 'smart-attendance-9fbcb',
    authDomain: 'smart-attendance-9fbcb.firebaseapp.com',
    storageBucket: 'smart-attendance-9fbcb.firebasestorage.app',
    measurementId: 'G-J6QKEPN6M7',
  );

}